app_project/models.py
from app_project.app import db
from datetime import datetime
import re


def slugify(string):
    pattern = r"[^\w+]"
    return re.sub(pattern, '-', string)


class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(140))
    slug = db.Column(db.String(140), unique=True)
    body = db.Column(db.Text)
    created = db.Column(db.DateTime, default=datetime.now())

    def __init__(self, *args, **kwargs):
        super(Post, self).__init__(*args, **kwargs)
        self.generate_slug()

    def generate_slug(self):
        if self.title:
            self.slug = slugify(self.title)

    def __repr__(self):
        return "<Post id: {}, title: {}>".format(self.id, self.title)
            

app_project/app.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy

from .config import Configuration


app = Flask(__name__)
app.config.from_object(Configuration)

db = SQLAlchemy(app)

app_project/main.py
from app_project.app import app, db
from app_project.posts.blueprint import posts_blue
import app_project.view


app.register_blueprint(posts_blue, url_prefix="/blog")

if __name__ == "__main__":
    app.run()

app_project/posts/blueprint.py
from flask import Blueprint, render_template

from app_project.models import Post

posts_blue = Blueprint("posts", __name__, template_folder="templates")


@posts_blue.route("/")
def index():
    posts = Post.query.all()

    return render_template("posts/index.html", posts=posts)


@posts_blue.route("/<slug>")
def post_detail(slug):
    post = Post.query.filter(Post.slug == slug).first()

    return render_template("posts/post_detail.html", post=post)

app_project/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <title>
        {% block title %}

        {% endblock title %} | Flask app
    </title>
</head>
<body>
<nav class="navbar sticky-top navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href=" {{ url_for('index') }}">Flask</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{{ url_for('posts.index') }}">Blog <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>
<div class="container">
    <div class="col">
        <h1>
            {% block content_title %}
            {% endblock content_title %}
        </h1>
        {% block content %}
        {% endblock content %}
    </div>

</div>

</body>
</html>

app_project/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Some name</title>
</head>
<body>
    <h2>Template and {{ n }}</h2>
</body>
</html>